name: Publish MAUI iOS Build

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
      with:
          ref: feature/maui-cicd
    - name: Use Xcode 16.4
      run: sudo xcode-select -s /Applications/Xcode_16.4.app
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    # - uses: maxim-lobanov/setup-xcode@v1
    #   with:
    #     xcode-version: '16.2'
    - name: Install the Apple certificate and provisioning profile
      env:
        P12_PASSWORD: "Stance@123 "
        KEYCHAIN_PASSWORD: "Stance@123 "
      run: |
       CERTIFICATE_PATH='./iOS_Certi/Certificates.p12'
       PP_PATH='./iOS_Certi/Pin_MAUI_AppStore.mobileprovision'
       KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
       security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
       security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
       security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
       security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
       security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
       security list-keychain -d user -s $KEYCHAIN_PATH
       mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
       cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/
    - name: Get Code Signing Key
      id: get_code_signing_key
      run: echo "CODE_SIGNING_KEY=$(security find-identity -p codesigning -v | grep '"' | head -n1 | awk -F '"' '{print $2}')" >> $GITHUB_ENV
    - name: Setup Maui
      run: dotnet workload install maui
    - name: Publish App
      run: |
               dotnet publish -f net9.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="\"Apple Distribution: CareBinders, LLC (552C3JPA84)\"" -p:CodesignProvision="Pin_MAUI_AppStore"
    - name: Get IPA Path
      id: find-ipa
      run: |
         echo "ipa-path=$(find $(pwd)/bin/Release/net9.0-ios/ios-arm64/publish -name "*.ipa")"  >> $GITHUB_ENV
         mkdir -p ~/private_keys
         cp  './AuthKey_B5XZTW8257.p8' ~/private_keys
         
    - name: Publish To Store
      run: |
          xcrun altool --validate-app -f "${{ env.ipa-path }}" -t ios --apiKey "B5XZTW8257"  --apiIssuer "69a6de71-ca08-47e3-e053-5b8c7c11a4d1"
          xcrun altool --upload-app -f "${{ env.ipa-path }}" -t ios --apiKey "B5XZTW8257"  --apiIssuer "69a6de71-ca08-47e3-e053-5b8c7c11a4d1"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.0
      with:
        name: com.pinventory.companionapp
        path: |
          ${{ env.ipa-path }}
